- name: Delete Azure VM
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - ./vars/common.yml
    - ./vars/az_general.yml
    - ./vars/vms.yml

  roles:
      - { role: check_vars }
      - { role: install_dependencies, when: dependencies_check }

  tasks:
    - name: Save number of Virtual Machines (VMs) to delete
      set_fact:
        len: "{{ vms | length }}"

    - name: Loop over deployed VMs
      ansible.builtin.include_tasks: delete_vm_tasks.yml
      loop: "{{ vms | dict2items }}"
      loop_control:
        loop_var: vm
        #index_var: idx
        extended: yes