- name: Create shared resources
  block:
  - name: Create SSH Key Pair
    include_tasks: create_key_pair.yml

  - name: Create VPC
    include_tasks: create_vpc.yml

  - name: Create Security Group
    include_tasks: create_security_group.yml

  - name: Create Subnet
    include_tasks: create_subnet.yml

  - name: Create Internet Gateway
    include_tasks: create_igw.yml

  - name: Create Route Table
    include_tasks: create_rt_table.yml
  when: first

- name: Provision EC2 Instance
  include_tasks: create_ec2_instance.yml

- name: Save VM username
  ansible.builtin.set_fact:
    vm_username: "{{ ec2_username }}"

- name: Save access details
  ansible.builtin.set_fact:
    ssh_info: "ssh -i {{ ec2_resource_prefix }}-private.pem {{ ec2_username }}@{{ ec2.instances[0].public_dns_name }}"

- name: Save public IP address
  ansible.builtin.set_fact:
    pub_ip: "{{ ec2.instances[0].public_ip_address }}"

- name: DNS for EC2 instance
  community.aws.route53:
    state: present
    zone: "{{ dns_zone }}"
    record: "{{ virtual_machine }}.{{ dns_zone }}"
    type: A
    overwrite: true
    value: "{{ pub_ip }}"
  when: dns_zone is defined and dns_zone != ""

- name: Save private SSH Key
  ansible.builtin.set_fact:
    ssh_key: "{{ playbook_dir }}/{{ ec2_resource_prefix }}-private.pem"
  no_log: True

- name: Wait until we can SSH to the last instance
  ansible.builtin.wait_for:
    host: "{{ pub_ip }}"
    port: 22
    state: started
  when: last